### ISSUE TITLE
Checklist: Overall

### ISSUE THREAD

**Issue by jeffreyohene** [jeffreyohene/ucimlR#2]
Project Scope

- [x] Create base package project
- [x] Gather dataset-related information from UCI page (Dataset name, type, subject area, feature type, number of features, number of observations, dataset information and variables table).
- [ ] Develop base functions
- [ ] Testing
- [ ] Documentation
- [ ] Final tests
- [ ] CRAN Submission
